name: delivery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+00010
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons:
  flutter_svg:
  provider: 
  expandable:
  intl:
  image_picker:
  shared_preferences:
  dio:
  flutter_bloc: ^8.1.3
  firebase_core: 2.15.1
  firebase_messaging: 14.2.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^5.1.0
  flutter_styled_toast: ^2.1.3
  flutter_launcher_icons: "^0.9.2"
  # flutter_launcher_icons: "^0.11.0"
  change_app_package_name: "^1.1.0"
  flutter_staggered_animations: ^1.1.1
  launch_review: ^3.0.1
  share: ^2.0.4
  simple_gradient_text: ^1.2.4
  loading_animations: ^2.2.0
  #url_launcher: ^6.1.6
  lottie: ^2.6.0
  easy_localization: ^3.0.2
  giff_dialog: ^1.0.1
  page_animation_transition: ^1.0.0
  flash: ^3.0.5+1
  path: ^1.8.3
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.3.0


flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

dependency_overrides:
  firebase_core_platform_interface:
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/languages/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf



  

